/*
DROP TABLE TRANSACAO;
DROP TABLE TIPOOPERACAO;
DROP TABLE TIPOTRANSACAO;
DROP TABLE TRANSFERENCIA;
DROP TABLE TIPOTRANSFERENCIA;
DROP TABLE CONTA;
DROP TABLE AGENCIA;
DROP TABLE TIPOCONTA;
DROP TABLE CLIENTE;
*/

--CLIENTE
CREATE TABLE CLIENTE (
    CODIGO            BIGINT AUTO_INCREMENT    PRIMARY KEY,
    NOME              VARCHAR(20)                 NOT NULL,
    SOBRENOME         VARCHAR(50)                 NOT NULL,
    CPF               VARCHAR(13)                 NOT NULL,
    ATIVO             INT                         NOT NULL
);

--TIPOCONTA
CREATE TABLE TIPOCONTA (
    CODIGO          BIGINT AUTO_INCREMENT    PRIMARY KEY,
    DESCRICAO       VARCHAR(30)                 NOT NULL,
    ATIVO           INT                         NOT NULL
);

INSERT INTO TIPOCONTA (DESCRICAO, ATIVO) VALUES ('Conta Corrente', 1);


--AGENCIA
CREATE TABLE AGENCIA (
    NUMERO            BIGINT AUTO_INCREMENT    PRIMARY KEY,
    NOME              VARCHAR(30)                 NOT NULL,
    ATIVO             INT                         NOT NULL
);

INSERT INTO AGENCIA (NOME, ATIVO) VALUES ('Ag Fortaleza', 1);


--CONTA
CREATE TABLE CONTA (
    NUMERO            BIGINT AUTO_INCREMENT     PRIMARY KEY,
    CODIGO_CLIENTE    BIGINT                    NOT NULL,
    NUMERO_AGENCIA    BIGINT                    NOT NULL,
    CODIGO_TIPOCONTA  BIGINT                    NOT NULL,
    SALDO             NUMERIC(20, 2)            NOT NULL,
    ABERTURA          TIMESTAMP                 NOT NULL,
    ENCERRAMENTO      TIMESTAMP,
    STATUS            INT                       NOT NULL,
    FOREIGN KEY (CODIGO_CLIENTE)    REFERENCES CLIENTE(CODIGO),                
    FOREIGN KEY (NUMERO_AGENCIA)    REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CODIGO_TIPOCONTA)  REFERENCES TIPOCONTA(CODIGO)
);


--TIPOTRANSFERENCIA
CREATE TABLE TIPOTRANSFERENCIA (
    CODIGO  BIGINT AUTO_INCREMENT    PRIMARY KEY,
    NOME    VARCHAR(30)                 NOT NULL,
    ATIVO   INT                         NOT NULL
);

INSERT INTO TIPOTRANSFERENCIA (NOME, ATIVO) VALUES ('Manual', 1);
INSERT INTO TIPOTRANSFERENCIA (NOME, ATIVO) VALUES ('Automática', 1);


--TRANSFERENCIA
CREATE TABLE TRANSFERENCIA (
    CODIGO                      BIGINT AUTO_INCREMENT   PRIMARY KEY,
    CONTA_ORIGEM                BIGINT                  NOT NULL,
    AGENCIA_ORIGEM              BIGINT                  NOT NULL,
    CONTA_DESTINO               BIGINT                  NOT NULL,
    AGENCIA_DESTINO             BIGINT                  NOT NULL,
    VALOR                       NUMERIC(20, 2)          NOT NULL,
    CODIGO_TIPOTRANSFERENCIA    BIGINT                  NOT NULL,
    DATA                        TIMESTAMP               NOT NULL,
    STATUS                      INT                     NOT NULL,
    FOREIGN KEY (CONTA_ORIGEM)              REFERENCES CONTA(NUMERO),
    FOREIGN KEY (AGENCIA_ORIGEM)            REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CONTA_DESTINO)             REFERENCES CONTA(NUMERO),
    FOREIGN KEY (AGENCIA_DESTINO)           REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CODIGO_TIPOTRANSFERENCIA)  REFERENCES TIPOTRANSFERENCIA(CODIGO)
);


--TIPOTRANSACAO
CREATE TABLE TIPOTRANSACAO (
    CODIGO        BIGINT AUTO_INCREMENT    PRIMARY KEY,
    DESCRICAO     VARCHAR(30)                 NOT NULL,
    ATIVO         INT                         NOT NULL
);

INSERT INTO TIPOTRANSACAO (DESCRICAO, ATIVO) VALUES ('Saque', 1);
INSERT INTO TIPOTRANSACAO (DESCRICAO, ATIVO) VALUES ('Depósito', 1);
INSERT INTO TIPOTRANSACAO (DESCRICAO, ATIVO) VALUES ('Transferência', 1);


--TIPOOPERACAO
CREATE TABLE TIPOOPERACAO (
    CODIGO      VARCHAR(1)      PRIMARY KEY,
    DESCRICAO   VARCHAR(30)     NOT NULL,
    ATIVO       INT             NOT NULL
);

INSERT INTO TIPOOPERACAO (CODIGO, DESCRICAO, ATIVO) VALUES ('C','Crédito', 1);
INSERT INTO TIPOOPERACAO (CODIGO, DESCRICAO, ATIVO) VALUES ('D','Débito', 1);


--TRANSACAO
CREATE TABLE TRANSACAO (
    CODIGO                  BIGINT AUTO_INCREMENT   PRIMARY KEY,
    CODIGO_TIPOTRANSACAO    BIGINT                  NOT NULL,
    CODIGO_TIPOOPERACAO     BIGINT                  NOT NULL,
    NUMERO_CONTA            BIGINT                  NOT NULL,
    NUMERO_AGENCIA          BIGINT                  NOT NULL,
    VALOR                   NUMERIC(20, 2)          NOT NULL,
    DATA                    TIMESTAMP               NOT NULL,
    STATUS                  INT                     NOT NULL,
    FOREIGN KEY (CODIGO_TIPOTRANSACAO)  REFERENCES TIPOTRANSACAO(CODIGO),
    FOREIGN KEY (CODIGO_TIPOOPERACAO)   REFERENCES TIPOOPERACAO(CODIGO),
    FOREIGN KEY (NUMERO_CONTA)              REFERENCES CONTA(NUMERO),
    FOREIGN KEY (NUMERO_AGENCIA)            REFERENCES AGENCIA(NUMERO)
);