/*
DROP TABLE TRANSACAO;
DROP TABLE TIPOOPERACAO;
DROP TABLE TIPOTRANSACAO;
DROP TABLE TRANSFERENCIA;
DROP TABLE TIPOTRANSFERENCIA;
DROP TABLE CONTA;
DROP TABLE AGENCIA;
DROP TABLE TIPOCONTA;
DROP TABLE CLIENTE;
*/

--DDL

--CLIENTE
CREATE TABLE CLIENTE (
    CODIGO            BIGINT AUTO_INCREMENT    PRIMARY KEY,
    NOME              VARCHAR(20)                 NOT NULL,
    CPF               VARCHAR(13)                 NOT NULL,
    UNIQUE (CPF)
);

--TIPOCONTA
CREATE TABLE TIPOCONTA (
    CODIGO          BIGINT          PRIMARY KEY,
    DESCRICAO       VARCHAR(30)     NOT NULL
);

--AGENCIA
CREATE TABLE AGENCIA (
    NUMERO            BIGINT AUTO_INCREMENT    PRIMARY KEY,
    NOME              VARCHAR(30)                 NOT NULL
);

--CONTA
CREATE TABLE CONTA (
    NUMERO            BIGINT AUTO_INCREMENT     PRIMARY KEY,
    CODIGO_CLIENTE    BIGINT                    NOT NULL,
    NUMERO_AGENCIA    BIGINT                    NOT NULL,
    CODIGO_TIPOCONTA  BIGINT                    NOT NULL,
    SALDO             NUMERIC(20, 2)            NOT NULL,
    ABERTURA          TIMESTAMP                 NOT NULL,
    ENCERRAMENTO      TIMESTAMP,
    FOREIGN KEY (CODIGO_CLIENTE)    REFERENCES CLIENTE(CODIGO),                
    FOREIGN KEY (NUMERO_AGENCIA)    REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CODIGO_TIPOCONTA)  REFERENCES TIPOCONTA(CODIGO),
    UNIQUE(CODIGO_CLIENTE, NUMERO_AGENCIA, CODIGO_TIPOCONTA)
);

--TIPOTRANSFERENCIA
CREATE TABLE TIPOTRANSFERENCIA (
    CODIGO  BIGINT          PRIMARY KEY,
    NOME    VARCHAR(30)     NOT NULL
);

--TRANSFERENCIA
CREATE TABLE TRANSFERENCIA (
    CODIGO                      BIGINT AUTO_INCREMENT   PRIMARY KEY,
    CONTA_ORIGEM                BIGINT                  NOT NULL,
    AGENCIA_ORIGEM              BIGINT                  NOT NULL,
    TIPOCONTA_ORIGEM            BIGINT                  NOT NULL,
    CONTA_DESTINO               BIGINT                  NOT NULL,
    AGENCIA_DESTINO             BIGINT                  NOT NULL,
    TIPOCONTA_DESTINO           BIGINT                  NOT NULL,
    VALOR                       NUMERIC(20, 2)          NOT NULL,
    CODIGO_TIPOTRANSFERENCIA    BIGINT                  NOT NULL,
    DATA                        TIMESTAMP               NOT NULL,
    STATUS                      INT                     NOT NULL,
    FOREIGN KEY (CONTA_ORIGEM)              REFERENCES CONTA(NUMERO),
    FOREIGN KEY (AGENCIA_ORIGEM)            REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CONTA_DESTINO)             REFERENCES CONTA(NUMERO),
    FOREIGN KEY (AGENCIA_DESTINO)           REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CODIGO_TIPOTRANSFERENCIA)  REFERENCES TIPOTRANSFERENCIA(CODIGO),
    FOREIGN KEY (TIPOCONTA_ORIGEM)          REFERENCES TIPOCONTA(CODIGO),
    FOREIGN KEY (TIPOCONTA_DESTINO)         REFERENCES TIPOCONTA(CODIGO)
);

--TIPOTRANSACAO
CREATE TABLE TIPOTRANSACAO (
    CODIGO        BIGINT        PRIMARY KEY,
    DESCRICAO     VARCHAR(30)   NOT NULL
);

--TIPOOPERACAO
CREATE TABLE TIPOOPERACAO (
    CODIGO      VARCHAR(1)      PRIMARY KEY,
    DESCRICAO   VARCHAR(30)     NOT NULL
);

--TRANSACAO
CREATE TABLE TRANSACAO (
    CODIGO                  BIGINT AUTO_INCREMENT   PRIMARY KEY,
    CODIGO_TIPOTRANSACAO    BIGINT                  NOT NULL,
    CODIGO_TIPOOPERACAO     VARCHAR(1)              NOT NULL,
    NUMERO_CONTA            BIGINT                  NOT NULL,
    NUMERO_AGENCIA          BIGINT                  NOT NULL,
    VALOR                   NUMERIC(20, 2)          NOT NULL,
    DATA                    TIMESTAMP               NOT NULL,
    STATUS                  INT                     NOT NULL,
    FOREIGN KEY (CODIGO_TIPOTRANSACAO)  REFERENCES TIPOTRANSACAO(CODIGO),
    FOREIGN KEY (CODIGO_TIPOOPERACAO)   REFERENCES TIPOOPERACAO(CODIGO),
    FOREIGN KEY (NUMERO_CONTA)              REFERENCES CONTA(NUMERO),
    FOREIGN KEY (NUMERO_AGENCIA)            REFERENCES AGENCIA(NUMERO)
);


--DML
INSERT INTO TIPOCONTA (CODIGO, DESCRICAO) VALUES (1, 'Conta Corrente');

INSERT INTO TIPOTRANSACAO (CODIGO, DESCRICAO) VALUES (1, 'Saque');
INSERT INTO TIPOTRANSACAO (CODIGO, DESCRICAO) VALUES (2, 'Depósito');
INSERT INTO TIPOTRANSACAO (CODIGO, DESCRICAO) VALUES (3, 'Transferência');
INSERT INTO TIPOTRANSACAO (CODIGO, DESCRICAO) VALUES (4, 'Estorno');

INSERT INTO TIPOOPERACAO (CODIGO, DESCRICAO) VALUES ('C','Crédito');
INSERT INTO TIPOOPERACAO (CODIGO, DESCRICAO) VALUES ('D','Débito');

INSERT INTO TIPOTRANSFERENCIA (CODIGO, NOME) VALUES (1, 'Manual');
INSERT INTO TIPOTRANSFERENCIA (CODIGO, NOME) VALUES (2, 'Automática');

INSERT INTO CLIENTE (NOME, CPF) VALUES ('Thiago', '12345678900');
INSERT INTO CLIENTE (NOME, CPF) VALUES ('João', '98765432100');

INSERT INTO AGENCIA (NOME) VALUES ('Ag Fortaleza');

INSERT INTO CONTA (CODIGO_CLIENTE, NUMERO_AGENCIA, CODIGO_TIPOCONTA, SALDO, ABERTURA ) VALUES (1, 1, 1, 5000.00, CURRENT_TIMESTAMP());
INSERT INTO CONTA (CODIGO_CLIENTE, NUMERO_AGENCIA, CODIGO_TIPOCONTA, SALDO, ABERTURA ) VALUES (2, 1, 1, 950.22,  CURRENT_TIMESTAMP());


--TRANSFERENCIAAGENDADA
CREATE TABLE TRANSFERENCIAAGENDADA (
    CODIGO                      BIGINT AUTO_INCREMENT   PRIMARY KEY,
    DATA_AGENDAMENTO            TIMESTAMP               NOT NULL,
    CONTA_ORIGEM                BIGINT                  NOT NULL,
    AGENCIA_ORIGEM              BIGINT                  NOT NULL,
    TIPOCONTA_ORIGEM            BIGINT                  NOT NULL,
    CONTA_DESTINO               BIGINT                  NOT NULL,
    AGENCIA_DESTINO             BIGINT                  NOT NULL,
    TIPOCONTA_DESTINO           BIGINT                  NOT NULL,
    VALOR                       NUMERIC(20, 2)          NOT NULL,
    STATUS                      INT                     NOT NULL,
    FOREIGN KEY (CONTA_ORIGEM)              REFERENCES CONTA(NUMERO),
    FOREIGN KEY (AGENCIA_ORIGEM)            REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CONTA_DESTINO)             REFERENCES CONTA(NUMERO),
    FOREIGN KEY (AGENCIA_DESTINO)           REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (TIPOCONTA_ORIGEM)          REFERENCES TIPOCONTA(CODIGO),
    FOREIGN KEY (TIPOCONTA_DESTINO)         REFERENCES TIPOCONTA(CODIGO)
);

