/*
DROP TABLE TRANSACAO;
DROP TABLE TIPOOPERACAO;
DROP TABLE TIPOTRANSACAO;
DROP TABLE TRANSFERENCIA;
DROP TABLE TIPOTRANSFERENCIA;
DROP TABLE CONTA;
DROP TABLE AGENCIA;
DROP TABLE TIPOCONTA;
DROP TABLE CLIENTE;
*/

--CLIENTE
CREATE TABLE CLIENTE (
    CODIGO            BIGINT AUTO_INCREMENT    PRIMARY KEY,
    NOME              VARCHAR(20)                 NOT NULL,
    SOBRENOME         VARCHAR(50)                 NOT NULL,
    CPF               VARCHAR(13)                 NOT NULL,
    ATIVO             INT                         NOT NULL,
    UNIQUE (CPF)
);

INSERT INTO CLIENTE (NOME, SOBRENOME, CPF, ATIVO) VALUES ('Thiago', 'Bernardo S', '12345678900', 1);
INSERT INTO CLIENTE (NOME, SOBRENOME, CPF, ATIVO) VALUES ('João', 'Do Teste', '98765432100', 1);

--TIPOCONTA
CREATE TABLE TIPOCONTA (
    CODIGO          BIGINT          PRIMARY KEY,
    DESCRICAO       VARCHAR(30)     NOT NULL,
    ATIVO           INT             NOT NULL
);

INSERT INTO TIPOCONTA (CODIGO, DESCRICAO, ATIVO) VALUES (1, 'Conta Corrente', 1);


--AGENCIA
CREATE TABLE AGENCIA (
    NUMERO            BIGINT AUTO_INCREMENT    PRIMARY KEY,
    NOME              VARCHAR(30)                 NOT NULL,
    ATIVO             INT                         NOT NULL
);

INSERT INTO AGENCIA (NOME, ATIVO) VALUES ('Ag Fortaleza', 1);


--CONTA
CREATE TABLE CONTA (
    NUMERO            BIGINT AUTO_INCREMENT     PRIMARY KEY,
    CODIGO_CLIENTE    BIGINT                    NOT NULL,
    NUMERO_AGENCIA    BIGINT                    NOT NULL,
    CODIGO_TIPOCONTA  BIGINT                    NOT NULL,
    SALDO             NUMERIC(20, 2)            NOT NULL,
    ABERTURA          TIMESTAMP                 NOT NULL,
    ENCERRAMENTO      TIMESTAMP,
    STATUS            INT                       NOT NULL,
    FOREIGN KEY (CODIGO_CLIENTE)    REFERENCES CLIENTE(CODIGO),                
    FOREIGN KEY (NUMERO_AGENCIA)    REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CODIGO_TIPOCONTA)  REFERENCES TIPOCONTA(CODIGO),
    UNIQUE(CODIGO_CLIENTE, NUMERO_AGENCIA, CODIGO_TIPOCONTA)
);

INSERT INTO CONTA (CODIGO_CLIENTE, NUMERO_AGENCIA, CODIGO_TIPOCONTA, SALDO, ABERTURA, STATUS) VALUES (1, 1, 1, 5000.00, CURRENT_TIMESTAMP(), 1);
INSERT INTO CONTA (CODIGO_CLIENTE, NUMERO_AGENCIA, CODIGO_TIPOCONTA, SALDO, ABERTURA, STATUS) VALUES (2, 1, 1, 950.22, CURRENT_TIMESTAMP(), 1);

--TIPOTRANSFERENCIA
CREATE TABLE TIPOTRANSFERENCIA (
    CODIGO  BIGINT          PRIMARY KEY,
    NOME    VARCHAR(30)     NOT NULL,
    ATIVO   INT             NOT NULL
);

INSERT INTO TIPOTRANSFERENCIA (CODIGO, NOME, ATIVO) VALUES (1, 'Manual', 1);
INSERT INTO TIPOTRANSFERENCIA (CODIGO, NOME, ATIVO) VALUES (2, 'Automática', 1);


--TRANSFERENCIA
CREATE TABLE TRANSFERENCIA (
    CODIGO                      BIGINT AUTO_INCREMENT   PRIMARY KEY,
    CONTA_ORIGEM                BIGINT                  NOT NULL,
    AGENCIA_ORIGEM              BIGINT                  NOT NULL,
    TIPOCONTA_ORIGEM            BIGINT                  NOT NULL,
    CONTA_DESTINO               BIGINT                  NOT NULL,
    AGENCIA_DESTINO             BIGINT                  NOT NULL,
    TIPOCONTA_DESTINO           BIGINT                  NOT NULL,
    VALOR                       NUMERIC(20, 2)          NOT NULL,
    CODIGO_TIPOTRANSFERENCIA    BIGINT                  NOT NULL,
    DATA                        TIMESTAMP               NOT NULL,
    STATUS                      INT                     NOT NULL,
    FOREIGN KEY (CONTA_ORIGEM)              REFERENCES CONTA(NUMERO),
    FOREIGN KEY (AGENCIA_ORIGEM)            REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CONTA_DESTINO)             REFERENCES CONTA(NUMERO),
    FOREIGN KEY (AGENCIA_DESTINO)           REFERENCES AGENCIA(NUMERO),
    FOREIGN KEY (CODIGO_TIPOTRANSFERENCIA)  REFERENCES TIPOTRANSFERENCIA(CODIGO),
    FOREIGN KEY (TIPOCONTA_ORIGEM)          REFERENCES TIPOCONTA(CODIGO),
    FOREIGN KEY (TIPOCONTA_DESTINO)         REFERENCES TIPOCONTA(CODIGO)
);


--TIPOTRANSACAO
CREATE TABLE TIPOTRANSACAO (
    CODIGO        BIGINT        PRIMARY KEY,
    DESCRICAO     VARCHAR(30)   NOT NULL,
    ATIVO         INT           NOT NULL
);

INSERT INTO TIPOTRANSACAO (CODIGO, DESCRICAO, ATIVO) VALUES (1, 'Saque', 1);
INSERT INTO TIPOTRANSACAO (CODIGO, DESCRICAO, ATIVO) VALUES (2, 'Depósito', 1);
INSERT INTO TIPOTRANSACAO (CODIGO, DESCRICAO, ATIVO) VALUES (3, 'Transferência', 1);
INSERT INTO TIPOTRANSACAO (CODIGO, DESCRICAO, ATIVO) VALUES (4, 'Extorno', 1);


--TIPOOPERACAO
CREATE TABLE TIPOOPERACAO (
    CODIGO      VARCHAR(1)      PRIMARY KEY,
    DESCRICAO   VARCHAR(30)     NOT NULL,
    ATIVO       INT             NOT NULL
);

INSERT INTO TIPOOPERACAO (CODIGO, DESCRICAO, ATIVO) VALUES ('C','Crédito', 1);
INSERT INTO TIPOOPERACAO (CODIGO, DESCRICAO, ATIVO) VALUES ('D','Débito', 1);


--TRANSACAO
CREATE TABLE TRANSACAO (
    CODIGO                  BIGINT AUTO_INCREMENT   PRIMARY KEY,
    CODIGO_TIPOTRANSACAO    BIGINT                  NOT NULL,
    CODIGO_TIPOOPERACAO     VARCHAR(1)              NOT NULL,
    NUMERO_CONTA            BIGINT                  NOT NULL,
    NUMERO_AGENCIA          BIGINT                  NOT NULL,
    VALOR                   NUMERIC(20, 2)          NOT NULL,
    DATA                    TIMESTAMP               NOT NULL,
    STATUS                  INT                     NOT NULL,
    FOREIGN KEY (CODIGO_TIPOTRANSACAO)  REFERENCES TIPOTRANSACAO(CODIGO),
    FOREIGN KEY (CODIGO_TIPOOPERACAO)   REFERENCES TIPOOPERACAO(CODIGO),
    FOREIGN KEY (NUMERO_CONTA)              REFERENCES CONTA(NUMERO),
    FOREIGN KEY (NUMERO_AGENCIA)            REFERENCES AGENCIA(NUMERO)
);